### PR TITLE
Add gemm tuning configs for weekly tuning CI

### PR DESCRIPTION
**Pull request by AlexAUT**
This adds our tuning configs to be used for the weekly tuning, the [confluence page](https://confluence.amd.com/display/MLSE/Triton+Performance+Regression+Pipeline) contains more details about the CI pipelines.

The fallback tuned configs are required for now for the nighlty regression CI because the navi4x machine was not stable enough to run a full tuning consistently. They changed the hardware and firmware to a newer revision so I will test it again. If it is stable we can remove the fallback in a separate PR.

I also removed the old regression script because the nightly regression CI uses the [triton-reporting-system](https://github.com/[ROCm/triton-reporting-system](https://github.com/ROCm/triton-reporting-system)) from the kernel team instead of the pytest script.

### CODE REVIEW

**Comment by AlexAUT** [comment]
~~Converted it to draft because we are waiting for the tuning CI pipeline to complete to have fallbacks~~.

**Review by ravil-mobile — APPROVED** [review]
LGTM

**Review by sjw36 — APPROVED** [review]
LGTM!

**Comment by sjw36** [comment]
@vgokhale ^^

**Review by vgokhale — APPROVED** [review]

**Pull request merged**
