### PR TITLE
[Dot] Fix FMA fp16xfp16 dot

### PR DESCRIPTION
**Pull request by binarman**
Disable reorder of dot arguemnts for amd gpu.

### CODE REVIEW

**Comment by binarman** [comment]
More details about why this function did not affect dot before.

Before IFU FMA dot operand "data flow" looked like this:

1. global load fp16       "blocked" layout
2. extend fp16 to fp32  "blocked" layout -> "blocked" layout
3. LDS store fp32         "blocked" layout -> "shared" layout
4. LDS load fp32    "shared" layout -> "dot operand" layout
5. FMA dot

After IFU this changed to:

1. global load fp16    "blocked" layout
2. LDS store fp16      "blocked" layout -> "shared" layout
3. LDS load fp16      "shared" layout -> "dot operand" layout
4. extend fp16 to fp32    "dot operand" layout -> "dot operand" layout
5. FMA dot

reorder function swizzles elements after elementwise operations(extend in our case), but **only** if layout is "dot operand" and input and output bitwidth is different.

**Review by jayfurmanek — APPROVED** [review]

**Review by zhanglx13 — APPROVED** [review]
As a quick fix, approved.

We'll need to understand how the `reorderValues` function works and if we need it on AMD gpus. 
Also, it seems the difference is now we push elementwise conversion after convert_layout #shared --> #dotOp. @binarman Do you know if this is an optimization introduced by the upstream? If so, can we just disable this optimization for FMA path on GPUs?

**Comment by jayfurmanek** [comment]
I think this patch is cleaner than forcing it back to the old data flow (only for FMA) for the purpose of exiting the reorderValues. If we don't want to run through reorderValues when in our dot operand layout, let's ensure we don't.

**Comment by jayfurmanek** [comment]
I think I would like a comment added here, however, to clarify why (and to remind us about it).

**Comment by binarman** [comment]
> Do you know if this is an optimization introduced by the upstream? If so, can we just disable this optimization for FMA path on GPUs?

TBD, I'll try to answer this question today.

I think we should keep this new optimization if possible, because new code consumes less LDS.

**Comment by jayfurmanek** [comment]
Agree, I suppose that was the goal with this change.

**Comment by binarman** [comment]
@jayfurmanek @zhanglx13  @wenchenvincent
The reason why context changed (as described in https://github.com/ROCmSoftwarePlatform/triton/pull/315#issuecomment-1699538934) is because `MoveOpAfterLayoutConversion` optimization from https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir/lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp started to work for FMA dot.

This optimization was changed in upstream recently and become more general.
Before IFU it worked only for Ampere: https://github.com/ROCmSoftwarePlatform/triton/blob/9cdf3a58c396a8265a788d4b5a5672d9b0c0c22a/lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp#L103-L104

**Comment by zhanglx13** [comment]
Well, the upstream disabled it again for V100 yesterday: https://github.com/openai/triton/pull/2223.
At least we should keep in mind that this kind of optimization can be buggy.

**Pull request merged**
