### PR TITLE
revert PR#245 and #241 for gemm performance regression

### PR DESCRIPTION
**Pull request by scxiao**
PR#241 caused performance regression for GEMM performance, and PR#245 depends on PR#241, so we have to revert both to avoid the GEMM performance regression. 

After reverting these two PRs, the best performance we can get for GEMM is (Unit: TFLOPS, larger is better.):

```
         M      cuBLAS     Triton
0    256.0    2.036070   1.466540
1    384.0    5.573140   3.976341
2    512.0   11.570494   8.224126
3    640.0   23.918249  12.900787
4    768.0   34.110305  19.391473
5    896.0   49.677011  25.328279
6   1024.0   59.918627  31.880696
7   1152.0   50.825260  34.094899
8   1280.0   68.985262  42.555845
9   1408.0   84.278666  42.446917
10  1536.0   58.149528  51.888298
11  1664.0   80.549702  42.535283
12  1792.0   90.938448  49.404061
13  1920.0  102.045671  51.229645
14  2048.0  115.828971  55.490534
15  2176.0   75.360647  56.093793
16  2304.0   84.232423  50.623200
17  2432.0  106.582439  56.215227
18  2560.0   99.156121  58.254122
19  2688.0  108.914707  57.816471
20  2816.0  109.484449  55.537322
21  2944.0  118.042138  58.213223
22  3072.0  114.425998  57.357950
23  3200.0  111.455590  56.873042
24  3328.0  105.675142  60.552494
25  3456.0  113.927424  58.105592
26  3584.0  121.430369  58.422145
27  3712.0  109.664204  60.066013
28  3840.0  114.325324  60.801311
29  3968.0  122.348805  61.021442
30  4096.0  129.113578  62.631608
```

### CODE REVIEW

**Comment by zhanglx13** [comment]
@alefimov-amd How does this affect your current work of vec load?

**Comment by binarman** [comment]
> How does this affect your current work of vec load?

If this is merged, I definitely need to rework some code, I think this is a work for ~1/2 a day

**Comment by binarman** [comment]
Could you take a look at https://github.com/ROCmSoftwarePlatform/triton/pull/269 ?
It introduces switch between fast and slow codegen paths for dot operands loading.
I've tested it on FA and it took performance back

**Comment by zhanglx13** [comment]
@binarman Thank you Alek. I'll take a look at https://github.com/ROCmSoftwarePlatform/triton/pull/269 next Monday and check the performance. We'll then decide if we still need to merge this one.

**Review by jayfurmanek — APPROVED** [review]

**Comment by jayfurmanek** [comment]
Given #269 doesn't yet mitigate, I'll merge this revert until we have things working.

**Pull request merged**
