### PR TITLE
Add groupM parameter in matmul.py to comply with profiler interface

### PR DESCRIPTION
**Pull request by binarman**

### CODE REVIEW

**Comment by binarman** [comment]
@zhanglx13

I've noticed that tritonProfile is not compatible with gemm driver, this commit is a workaround for this problem.

Another problem I faced is kpack kernel do not accept parameters, but I am not sure where fix this =(

**Comment by binarman** [comment]
Do you mean, that current implementation of `tritonProfile.sh` is not intended for plain GEMM testing?

**Comment by zhanglx13** [comment]
If "plain gemm" means the one without `kpack` and `mPerWave` as parameters, then no.
It only accepts `matmul.py` (for small gemms) and `matmul_grouped.py` (for large gemms) as the drivers, both of which take `kpack` and `mPerWave` as parameters.

**Comment by jayfurmanek** [comment]
maybe we should have a separate script then for "plain" gemm?

**Comment by binarman** [comment]
I don't think this PR is needed anymore, so closing it

**Pull request closed without merging**
