### PR TITLE
IFU 230620

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
dynamic wavesize changes are in flight upstream. I will rebase this once those are settled.

**Review by zhanglx13 — APPROVED** [review]
LGTM

One thing to note is that @xinyazhang's fix for the warpSize (https://github.com/ROCmSoftwarePlatform/triton/pull/256) is also ready. Not sure which one should get merged first.

**Review by alefimov-amd — APPROVED** [review]
LGTM

**Comment by jayfurmanek** [comment]
It seems #256 is perhaps not quite ready after all. I'd like to merge this one, then #247

**Comment by scxiao** [comment]
Tried this PR for GEMM performance, no regression observed.

**Pull request merged**
