### PR TITLE
add tutorial group gemm example

### PR DESCRIPTION
**Pull request by scxiao**
Cherry pickup tutorial group gemm example

### CODE REVIEW

**Review by jayfurmanek — APPROVED** [review]

**Comment by zhanglx13** [comment]
I just tried it and here is what I got:

group-gemm-performance:
        N    cuBLAS    Triton
0   128.0  0.061440  0.031040
1   256.0  0.035521  0.042240
2   512.0  0.060640  0.065440
3  1024.0  0.108961  0.392642

Does it look ok to you, @scxiao?

**Comment by scxiao** [comment]
> I just tried it and here is what I got:
> 
> group-gemm-performance: N cuBLAS Triton 0 128.0 0.061440 0.031040 1 256.0 0.035521 0.042240 2 512.0 0.060640 0.065440 3 1024.0 0.108961 0.392642
> 
> Does it look ok to you, @scxiao?

Here is the a100 performance, unit is time (ms).
group-gemm-performance:
        N    cuBLAS    Triton
0   128.0  0.020480  0.013312
1   256.0  0.023552  0.018432
2   512.0  0.032768  0.026624
3  1024.0  0.071680  0.087040

So, our performance is bad. Let me do some investigation, we should be much better than these numbers.

**Comment by scxiao** [comment]
Latest performance on MI250X
group-gemm-performance:
        N    cuBLAS    Triton
0   128.0  0.061441  0.017120
1   256.0  0.034881  0.021281
2   512.0  0.060481  0.039040
3  1024.0  0.108481  0.153281

2x to 2.5x faster than first try

**Comment by scxiao** [comment]
Latest performance numbers on MI250
group-gemm-performance:
        N    cuBLAS    Triton
0   128.0  0.061440  0.016480
1   256.0  0.035040  0.020160
2   512.0  0.060481  0.035040
3  1024.0  0.108640  0.113441

**Pull request merged**
