### PR TITLE
[FRONTEND] Fix llir_to_amdgcn_and_hsaco arguments in aot.py

### PR DESCRIPTION
**Pull request by binarman**
Add missing triple and features arguments to aot.py.

### CODE REVIEW

**Comment by binarman** [comment]
@i-chaochen PTAL

I also have a question about architecture and available features.

Should we have user-available handles to enable/disable some processor features or we can infer available features from given architecture (gfx906/gfx90a/gfx940/etc.)?

To clarify, what I mean by latter option: it is implemented in this PR

**Comment by rsanthanam-amd** [comment]
@binarman 

we should not infer anything.  we should discover those traits.

maybe you could call this:

https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir/python/triton/compiler.py#L1635-L1653

**Comment by rsanthanam-amd** [comment]
@binarman 

i would prefer not to infer anything.

for aot, the triple can be hardcoded to `amdgcn-amd-amdhsa` and i would suggest making the features argument optional (if it is not specified, just pass an empty string which should still work).

**Comment by i-chaochen** [comment]
> @i-chaochen PTAL
> 
> I also have a question about architecture and available features.
> 
> Should we have user-available handles to enable/disable some processor features or we can infer available features from given architecture (gfx906/gfx90a/gfx940/etc.)?
> 
> To clarify, what I mean by latter option: it is implemented in this PR

Since this is AOT, it's better to get its AMD GPU ISA full details in advance, accurately, and then to compile. 


You shall use this new implemented ```_get_amdgpu_arch_fulldetails()``` to get the correct ISA info to compile instead of hardcoding.
https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir/python/triton/compiler.py#L1635-L1653


Regarding to enable/disable processor features, user can define by itself to pass what arguments to ```llir_to_amdgcn_and_hsaco()```
https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir/lib/Target/HSACO/HSACOTranslation.cpp#L162-L168

**Comment by binarman** [comment]
@i-chaochen @rsanthanam-amd  PTAL

**Review by rsanthanam-amd — APPROVED** [review]

**Comment by rsanthanam-amd** [comment]
LGTM.  Once the unit tests pass, i will merge.

**Pull request merged**
