### PR TITLE
[Alloc] Enhanced SharedMem Allocation for mutually exclusive but aliased buffers

### PR DESCRIPTION
**Pull request by sjw36**
- Use disjoint alias analysis to minimize shared memory requirements

Fixes: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5627

### CODE REVIEW

**Review by zhanglx13 — COMMENTED** [review]
Can you add a test to show that the old allocation pass allocates too much LDS but the new one doesn't?

**Review by Jokeren — COMMENTED** [review]
Thank you Simon!

**Comment by sjw36** [comment]
@zhanglx13 please review.

**Review by zhanglx13 — APPROVED** [review]
LGTM

Here is the speed up for dense GEMM:

M | triton-mlir num_stages=1 | num_stages=0 (PR#337) | speedup
-- | -- | -- | --
1024 | 44 | 49 | 1.11
2048 | 94 | 103 | 1.10
4096 | 109 | 120 | 1.10
8192 | 107 | 112 | 1.05

**Pull request merged**
