### PR TITLE
use local bit code

### PR DESCRIPTION
**Pull request by micmelesse**
address https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3630

### CODE REVIEW

**Comment by rsanthanam-amd** [comment]
@micmelesse please put the bc files in a new folder - /triton/python/triton/third_party/rocm

**Review by rsanthanam-amd — CHANGES_REQUESTED** [review]
Change location of bc files.

**Comment by micmelesse** [comment]
I don't know why the unit test are being interrerupted, locally it passes. @rsanthanam-amd is it a ci issue?
```
================ 4023 passed, 14 skipped in 1584.88s (0:26:24) =================
```

**Comment by rsanthanam-amd** [comment]
> I don't know why the unit test are being interrerupted, locally it passes. @rsanthanam-amd is it a ci issue?
> 
> ```
> ================ 4023 passed, 14 skipped in 1584.88s (0:26:24) =================
> ```

Yeah, they are working on the CI infrastructure.  Once the issue is resolved, I will restart the CI job and ensure it passes.

**Comment by rsanthanam-amd** [comment]
@micmelesse please squash the multiple commits into a single one to make it easier to cherry pick to `triton-mlir-pyt20`.  thanks!

**Comment by micmelesse** [comment]
@rsanthanam-amd done

**Review by rsanthanam-amd — APPROVED** [review]

**Pull request merged**
