### PR TITLE
Make configurable warp size compatible with PyTorch's inductor

### LINKED ISSUE #255: Configurable parameter for threads per warp is incompatible with PyTorch's inductor
TOT triton-mlir branch causes all PT2.0 unit tests to fail

```
  File "/tmp/torchinductor_root/lz/clzglerv24u6t6d3ln4qpi7kzo2im3g5lpntfioexos2eywqvz3k.py", line 66, in call
    triton_poi_fused_add_0.run(arg0_1, arg1_1, buf0, 10, grid=grid(10), stream=stream0)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/triton_heuristics.py", line 353, in run
    return launcher(
  File "<string>", line 6, in launcher
TypeError: function takes exactly 15 arguments (14 given)
```

I have triaged this down to this commit https://github.com/ROCmSoftwarePlatform/triton/commit/75b86da598c6f30e76bc883faca9c274a1fc0ede which introduces the additional parameter `warpSize` 

To resolve this we would either need to
- Upstream this PR and unify the args list with CUDA - CUDA_DEFAULT_WARP_SIZE was already implemented so it seems this is a possibility
- Alternatively, do not modify the expected args in compiler.py, make_launcher.py (and maybe jit.py and aot.py) and get the configurable warp size in an alternative manner

Until this is resolved we have to be careful that future updates do not rely on the warpSize change so we are still able to get updates from the `triton-mlir` branch to `triton-mlir-pyt-latest` without running into issues. 

**To reproduce:**
1. `docker pull rocm/pytorch-private:pyt2-tot-0629`
2. `pytest test/inductor/test_torchinductor.py -k "test_cuda_broadcast1_broadcast1" --verbose`

cc: @xinyazhang @jayfurmanek @zhanglx13 @micmelesse @dllehr-amd

### PR DESCRIPTION
**Pull request by xinyazhang**
Remove warp size argument from python function.

The additional warp_size argument breaks the compatibility with TOT, but after examination this argument is not necessary, because this value can be retrieved from `hipStream_t`.

Fixes #255

### CODE REVIEW

**Comment by xinyazhang** [comment]
UT `pytest python/test/unit/language/test_core_amd.py --verbose` passed on Navi 32:
```
4580 passed, 63 skipped, 143 warnings in 3733.95s (1:02:13)
```
and MI200
```
4532 passed, 58 skipped, 143 warnings in 1222.34s (0:20:22)
```

**Comment by jataylo** [comment]
Hey @xinyazhang cc: @zhanglx13 thank for taking a look at this

I tried to fix but run into some issues
```
  File "/opt/conda/envs/py_3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
ImportError: /tmp/torchinductor_root/triton/0/a2d6dc021d54927d03e6ebe938b4c17a/triton_.so: undefined symbol: hipStreamGetDevice
```

I saw that you mentioned this issue on https://github.com/ROCmSoftwarePlatform/triton/issues/255
`Please be aware this solution won't work with ROCM < 5.6, due to requirement of hipStreamGetDevice`

At the minute upstream pytorch is still 5.4 and moving onto 5.5 and may take awhile before getting to 5.6, is there a potential workaround here?

**Comment by jayfurmanek** [comment]
So far we've not needed anything on the python side that is conditional on a specific ROCM version. This fix is clean and good so it's unfortunate it won't help Pytorch at the moment. We may have to create a ROCM configuration state, which includes the active version, so we can switch against it.

Then we can:
if rocm56
    do the hipStreamGetDevice
else
    hard-code the value

**Comment by xinyazhang** [comment]
@jataylo The updated PR should have fixed the problem. `hipGetStreamDeviceId` is relatively old (> 2 yrs) and should have been well supported in deployed systems.

**Comment by xinyazhang** [comment]
`test_cuda_broadcast1_broadcast1` verified locally
```
(py_3.9) root@6b9547c02da9:/var/lib/jenkins/pytorch# pytest test/inductor/test_torchinductor.py -k "test_cuda_broadcast1_broadcast1" --verbose
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /opt/conda/envs/py_3.9/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/var/lib/jenkins/pytorch/.hypothesis/examples')
rootdir: /var/lib/jenkins/pytorch
configfile: pytest.ini
plugins: shard-0.1.2, xdoctest-1.1.0, cpp-2.3.0, flakefinder-1.1.0, hypothesis-5.35.1, rerunfailures-11.1.2, xdist-3.2.1
collected 917 items / 916 deselected / 1 selected                                                                                                                                                                                             
Running 1 items in this shard: test/inductor/test_torchinductor.py::SweepInputsCudaTest::test_cuda_broadcast1_broadcast1

test/inductor/test_torchinductor.py::SweepInputsCudaTest::test_cuda_broadcast1_broadcast1 PASSED [2.9655s]                                                                                                                             [100%] 

===================================================================================================== 1 passed, 916 deselected in 8.88s ======================================================================================================
```

**Comment by jayfurmanek** [comment]
So I think technically what hipGetStreamDeviceId() returns is different than what hipStreamGetDevice() returns.
I think the difference is that the deviceId may not be consistent across processes, which perhaps is ok in this case because we are just using it to query the warpsize of the device in question.

**Comment by jayfurmanek** [comment]
@xinyazhang I see this has passed the unit tests and LIT tests at least - have you done any other testing with this PR?

**Review by jayfurmanek — APPROVED** [review]

**Comment by xinyazhang** [comment]
@jayfurmanek 
> have you done any other testing with this PR?
Not yet. I only verified it really fixed the UT in pytorch test/inductor

**Comment by dllehr-amd** [comment]
I realize this is already merged. But do we foresee any issue with `_launch` making a hipGetDeviceProperties call every time?  Feels like we're being a bit redundant when a warp size should be something we figure out ahead of time?
https://github.com/ROCmSoftwarePlatform/triton/blob/triton-mlir/python/triton/runtime/backends/hip.c#L29
For instance is already in place and called to get our device information.

I doubt we'd want to care about the exact current device we're compiling against, as I doubt PyTorch even has the capability of keeping kernels unique when scheduling them (i.e. we lower and build a single compiled kernel, and schedule across multiple gpus.)

I'm not sure if this is something we can use and tie it into the `CompiledKernel` class?

**Comment by xinyazhang** [comment]
> Feels like we're being a bit redundant when a warp size should be something we figure out ahead of time?

I'm afraid we can't make such assumptions, because it is possible for users to install MI200 and Navi 31 on the same system at the same time. This situation can be rare but is possible (Navi for video output and MI for compute, I have seen similar NVIDIA configurations in the lab next to me). In this case we can only determine the warp size according to the stream.

Sure we haven't verified if the Navi + MI combination works on current triton, but at least we can make the feature easier to implement by not assuming there is a unique, predetermined warp size in the system.

> I'm not sure if this is something we can use and tie it into the CompiledKernel class?

It's already there: https://github.com/ROCmSoftwarePlatform/triton/blob/6ee06a129529332d31fba39ff373251bd8f6b2a0/python/triton/compiler/compiler.py#L541
The problem is how can we pass this Python property to the C code. I added an warp size argument in the previous PR but it breaks the compatibility with pytorch inductor.

**Comment by dllehr-amd** [comment]
Okay, my larger issue is still performance.  I would like to see how this affects even our current benchmark runs.

@jataylo  Lets test this out, and then try it out hard coding the warp size.  If it's negligible then I'm okay leaving it.  If we notice a measurable drop in perf, I'd push for an alternative solution.

**Pull request merged**
