### PR TITLE
[MLIR] Fixed support for mixed data-types in stream-pipeline

### PR DESCRIPTION
**Pull request by sjw36**
This fixes the case where not all loads are pipelined but they have shared dependencies.

### CODE REVIEW

**Comment by sjw36** [comment]
Hmm, still need to update the lit test a bit.

**Comment by sjw36** [comment]
@zhanglx13 @scxiao  can you review.

**Review by zhanglx13 — COMMENTED** [review]
I got slightly worse numbers for small gemms.

**Review by zhanglx13 — APPROVED** [review]
LGTM and no regression on GEMM

**Pull request merged**
