### PR TITLE
Refactoring compilation target info propagation from frontend to compiler insides

### PR DESCRIPTION
**Pull request by binarman**
Main idea of this refactoring:
- save target info in mlir during `triton` to `tritongpu` translation
- after this translation, use all target info from `mlir` itself

### CODE REVIEW

**Comment by binarman** [comment]
related issue #163

**Review by micmelesse — COMMENTED** [review]
I think the pr looks good overall and we needed to do this work at some point, so happy it has been done. However I think there is one major issue. We are working on changing how we get the compilation target information and changing the rocminfo dependency. Please hold of filling this PR upstream untill that work is done. I just need some time to finish that up.

**Comment by rsanthanam-amd** [comment]
@binarman please fix the conflicts.  thanks!

**Comment by binarman** [comment]
This functionality is partially implemented in upstream.
Plus we currently using different approach, so we do not need this PR anymore, closing

**Pull request closed without merging**
