### PR TITLE
remove multiple archtictures to isa head and adding gemm tuning scripts

### PR DESCRIPTION
**Pull request by scxiao**
1) remove the code to include multiple versions of arch features to isa head
2) Added a script to tune gemm performance (compatible with a script outside of this repo, may refine the script name later)

### CODE REVIEW

**Review by keryell — COMMENTED** [review]
I do not understand the PR title (besides the typo to be fixed).
Or were the 2 other files not expected to be part of this PR?

**Comment by scxiao** [comment]
> I do not understand the PR title (besides the typo to be fixed). Or were the 2 other files not expected to be part of this PR?

This PR is for the MI300X bringup and for testing the MSFT workloads. To do the testing, there is a joint (AMD/MSFT) repository that requires these two scripts. I agree the name and location of the scripts are not good, but that is required by the other repository. I will fix that (rename the script and move them to a better location) in a later PR in this repo and the other repo, so they can still work together,

**Comment by zhanglx13** [comment]
Do we need `matmul_grouped.py`?

**Comment by scxiao** [comment]
> Do we need `matmul_grouped.py`?

I am not actually sure about that. Hi @alefimov-amd, what is your opinion on that?

**Comment by zhanglx13** [comment]
I asked because I saw you added it here: https://github.com/ROCmSoftwarePlatform/msft_amd_ai_operators/pull/172/files

**Comment by scxiao** [comment]
> I asked because I saw you added it here: https://github.com/ROCmSoftwarePlatform/msft_amd_ai_operators/pull/172/files

I see, in the script [scripts/amd/gemm/tune_gemm.sh](https://github.com/ROCmSoftwarePlatform/triton/pull/261/files#diff-206e0f2fa4b942a085eebc0e799db7be01cbe47e10ced2bba48b72efeed38cbb), there is the following line
```
DRIVER=$(echo $DRIVER | sed -e "s/matmul_grouped.py/matmul.py/g")
```
to replace `matmul_grouped.py` with `matmul.py` for the driver.

**Pull request merged**
