### PR TITLE
[MFMA] [Dot] Support vector loads in normal path

### PR DESCRIPTION
**Pull request by binarman**
This PR adds generation of vector loads in normal path of MFMA dot operand loading.
This requires shared layout to have contiguous elements which should be loaded by one lane.

### CODE REVIEW

**Review by zhanglx13 — CHANGES_REQUESTED** [review]
Just one more test and I think this PR is good to go.

This is a note to myself (and maybe Alek):
- vector load happens only for k-major matrices in the normal path
- the vector length is determined by
    - if no swizzling, `k_base` or `numOfElems`
    - if swizzled, min(`k_base`, `vec`)

So in the future, we would like to extend the vector load to support
- MN-major matrices
- vector length that is larger than `k_base`/`numOfElems`.

**Comment by binarman** [comment]
Thank you for summary!

> So in the future, we would like to extend the vector load to support
> - MN-major matrices **
> - vector length that is larger than k_base/numOfElems.

When can we discuss this?

I know about only one type of instruction that can help with MN major matrices - `ds_read2`.
It has some limitations, that makes it hard to use:
- It loads only 2 values, which is good, but is less compared to what we can achieve with other techniques
- it reads two 32 or 64 bit values, so we have benefits with only fp32 and fp64 dtypes

My current plan about mfma dot has these items:

1. support mfma 16
2. implement transformation that transposes lds matrices if needed. 

I think, these steps will utilize LDS at full:
- mfma16 has longer k dimension, and we can swizzle with larger `vec` parameter
- transposes make MN-first matrices into K-first matrices, so we can use existing code without modification

**Comment by alefimov-amd** [comment]
@zhanglx13 
I've updated test, so now it tests cases with transposed inputs

**Review by zhanglx13 — APPROVED** [review]
Approved!

I'll create a ticket to discuss the issues.

**Pull request merged**
