### PR TITLE
Add navi3x bitcode files

### PR DESCRIPTION
**Pull request by xinyazhang**
This fixes
  * https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4522
  * https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4523

### CODE REVIEW

**Comment by xinyazhang** [comment]
AMD Offline Tests failed because of "No space left on device"?

**Comment by binarman** [comment]
@xinyazhang 
docker image we used for testing changed recently and for some reason now it consumes too much disk space.

This #230  is a fix for this problem

**Comment by binarman** [comment]
Are you sure, main is the branch, you want to merge with?

Most actively developed branches are `triton-mlir` and `dot-rocMLIR`, I think

**Comment by xinyazhang** [comment]
> Are you sure, main is the branch, you want to merge with?
> 
> Most actively developed branches are `triton-mlir` and `dot-rocMLIR`, I think

Sorry I misclicked

**Review by scxiao — APPROVED** [review]

**Comment by jayfurmanek** [comment]
Yes

**Review by jayfurmanek — APPROVED** [review]

**Comment by scxiao** [comment]
Hi @xinyazhang, after the CI build passed, I think you can merge this PR. Thanks.

**Comment by evshiron** [comment]
Hello everyone, I am sorry to disturb you, but I have some questions that I hope to get answers from all of you.

I have been experimenting on Triton with Navi31 support for several days. I encountered various problems before and tried @xinyazhang's branches, but it wasn't until yesterday that I made some positive progress.

The added files in this PR do improve the usability of Navi31. However, in `test_core_amd.py`, `test_reduce1d` and `test_reduce2d` are all in error state.

I referred to [this](https://github.com/ROCmSoftwarePlatform/triton/commits/xinyazhang/navi-debug-argmax) and [that](https://github.com/ROCmSoftwarePlatform/triton/pull/153) and found that reducing the warp size from 64 to 32 might be a feasible approach, and I made a separate fork [here](https://github.com/are-we-gfx1100-yet/triton).

This branch indeed solved the problems in `test_reduce1d` and `test_reduce2d`, but at the same time, it also introduced new problems: there were more or less errors in `test_convert2d`, `test_reduce_layouts`, and `test_make_range`.

I am completely unfamiliar with this field and do not know what MFMA is. I guess either there are omissions in the above modifications, or the IR code in the test case needs to be updated. Therefore, I would like to ask you to spare some time to point me in the right direction. Thank you.

The log can be found [here](https://github.com/are-we-gfx1100-yet/triton/issues/1) if you are interested.

**Comment by evshiron** [comment]
Thank you for the explanation :)

I did a `scripts/amd/test.sh` on https://github.com/ROCmSoftwarePlatform/triton/commit/ac1e551e8a51ad5969325bdb5a0e75010dff70aa (the current commit on the `triton-mlir` branch) just now, and the complete log is pasted here:

* https://gist.github.com/evshiron/d603eee422b15b9c8c79a834b03c9e16

**Comment by binarman** [comment]
Hi @evshiron !

Let me add two words about MFMA instructions - unfortunately, these instructions are available on MI series only(and it is tuned for warp size 64), so you should not really care about it on navi gpus with warp size 32.

Test that failed are not related to your hardware, so I suppose this is a problem of tests itself, we probable need to disable them if run on unsupported hardware.

**Comment by evshiron** [comment]
@binarman 

Thank you for your reply! I have just seen PR #243 and #244. They really seem to improve my quality of life, and I sincerely appreciate your work.

**Comment by scxiao** [comment]
Hi @evshiron, FYI. 
the following are the failed tests that failed after applying #243 and #244 (24 failed)

FAILED python/test/unit/language/test_core_amd.py::test_index1d[x[None, :, :]-int32] - AssertionError: assert False
FAILED python/test/unit/language/test_core_amd.py::test_index1d[x[None, :, :]-uint32] - AssertionError: assert False
FAILED python/test/unit/language/test_core_amd.py::test_index1d[x[None, :, :]-uint16] - AssertionError: assert False
FAILED python/test/unit/language/test_core_amd.py::test_index1d[x[:, :, None]-int32] - AssertionError: assert False
FAILED python/test/unit/language/test_core_amd.py::test_index1d[x[:, :, None]-uint32] - AssertionError: assert False
FAILED python/test/unit/language/test_core_amd.py::test_index1d[x[:, :, None]-uint16] - AssertionError: assert False
FAILED python/test/unit/language/test_core_amd.py::test_permute[float16-shape0-perm0] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_permute[float16-shape1-perm1] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_permute[float32-shape2-perm2] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[64-64-64-2-False-False-trans-True-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[64-64-64-2-False-False-trans-False-float16] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[64-64-64-2-False-False-trans-False-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[64-64-64-2-False-False-add-matrix-False-float16] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-none-True-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-none-False-float16] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-none-False-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-trans-True-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-trans-False-float16] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-trans-False-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-add-matrix-True-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-add-matrix-False-float16] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[32-32-32-2-False-False-add-matrix-False-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_dot[128-128-32-2-True-False-none-False-float32] - AssertionError: 
FAILED python/test/unit/language/test_core_amd.py::test_gemm[64-32-128-4-64-32-64] - AssertionError:

**Comment by evshiron** [comment]
@scxiao 

Thank you!

I am currently traveling, and it's a pity that I can't try it myself.

I am curious about the results of merging my modification for the same purpose (which failed in `test_convert2d`, `test_reduce_layouts`, and `test_make_range`, the log is collapsed [here](https://github.com/are-we-gfx1100-yet/triton/issues/1#issuecomment-1598258226) in case you missed it) with the branches above.

**Comment by evshiron** [comment]
@scxiao 

Greetings. I fixed #244 with lit tests and unit tests passed on my RX 7900 XTX, https://github.com/are-we-gfx1100-yet/triton/commit/b58036cd98b284d5ec1a7d77f4a621a69233de71, including:

* One missing [line](https://github.com/are-we-gfx1100-yet/triton/commit/b58036cd98b284d5ec1a7d77f4a621a69233de71#diff-a5d78fad74ed959619ebfc6de068145c29400283d3e0c3ebf9643d6035a78e53R125) to make tests above work again (which makes `MfmaLayout` refuse to work)
* Change the warp size of `layouts` to `32` to allow `test_convert2d` and `test_reduce_layouts` to work
* Skip `MfmaLayout` related tests

**Comment by scxiao** [comment]
> @scxiao
> 
> Greetings. I fixed #244 with lit tests and unit tests passed on my RX 7900 XTX, [are-we-gfx1100-yet@b58036c](https://github.com/are-we-gfx1100-yet/triton/commit/b58036cd98b284d5ec1a7d77f4a621a69233de71), including:
> 
> * One missing [line](https://github.com/are-we-gfx1100-yet/triton/commit/b58036cd98b284d5ec1a7d77f4a621a69233de71#diff-a5d78fad74ed959619ebfc6de068145c29400283d3e0c3ebf9643d6035a78e53R125) to make tests above work again (which makes `MfmaLayout` refuse to work)
> * Change the warp size of `layouts` to `32` to allow `test_convert2d` and `test_reduce_layouts` to work
> * Skip `MfmaLayout` related tests

Hi @evshiron, many thanks for the changes. We will integrate the changes in a way that works for all our GPUs.

**Pull request merged**
