### PR TITLE
Fix for LLVM compiler's inability to auto-vectorize float16 loads and stores on AMDGPU.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
If applicable, load a 32 bit value and crack it into smaller chunks based on the actual specified data type.

For stores, just store the already packed elements.

### CODE REVIEW

**Comment by whchung** [comment]
Very good concept!

**Comment by dfukalov** [comment]
I would suggest to add introduced bitcast operations to tests, since they are significant in the approach.

**Comment by rsanthanam-amd** [comment]
> I would suggest to add introduced bitcast operations to tests, since they are significant in the approach.

Done.  PTAL.  Thanks!

**Comment by rsanthanam-amd** [comment]
@whchung 

I added 2 new tests to check float16/int16 vectorized loads/stores:

test/Target/mlir_to_amdgcn_float16_vectorized_load_store.mlir
test/Target/mlir_to_amdgcn_int16_vectorized_load_store.mlir

PTAL.

Thanks!

**Review by whchung — APPROVED** [review]
LGTM! Thanks for making this to happen! Nice optimization !

Nitpick: in AOT tests where final GCN ISAs are checked, can we add more gfx targets to cover targets we really care about

**Comment by rsanthanam-amd** [comment]
> LGTM! Thanks for making this to happen! Nice optimization !
> 
> Nitpick: in AOT tests where final GCN ISAs are checked, can we add more gfx targets to cover targets we really care about

I added checks for gfx908 and gfx90a.

**Pull request merged**
